#+HTML: <div class="container-fluid"><div class="row"><div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-lg-4 col-lg-offset-4">
#+TITLE: About
#+HTML: <br><br>

#+HTML: <h2>About Me</h2>

I'm a developer from the Upper Midwest that loves coding, rock climbing,
cooking, and skiing. My focus is on building web applications and
learning as much as possible about different tools, techniques, and
programming paradigms.

#+HTML: <br>

Clojure/ClojureScript has been my favorite language to program in so
far. Clojure has the metaprogramming of LISP, easy access to tools from
mainstream languages like Java and JavaScript, a smart community, and is
built for simplicity. This gives me more productivity, language
constructs as libraries, concurrency (even in JS), robust testing, and
lots of other fun stuff.

#+HTML: <br>

Most recently, I've been working through modern JavaScript features with
Udacity's Senior Web Developer Nanodegree. Since 2012, I've been using
JavaScript on and off for projects and took the Nanodegree program to
get up to speed with the latest front-end features. It taught a great
curriculum from Google for building Progressive Web Apps that were
offline-first, responsive, accessible, and built with popular frameworks
like Node.js and Angular.

#+HTML:<br>
** Contact Me
#+ATTR_HTML: :target _blank
Resume: [[file:resume][EdBabcock.com/resume]]
#+HTML:
Email: [[mailto:Ed@EdBabcock.com][Ed@EdBabcock.com]]
#+ATTR_HTML: :target _blank
LinkedIn: [[https://LinkedIn.com/in/EdBabcock][LinkedIn.com/in/EdBabcock]]
#+ATTR_HTML: :target _blank
Angel List: [[https://angel.co/ed-babcock][Angel.co/Ed-Babcock]]
#+ATTR_HTML: :target _blank
GitHub: [[https://github.com/greenyouse][github.com/greenyouse]]

#+HTML: </div></div></div>
